nginx-ingress:
  controller:
    # config:
    #   entries:
    #     opentracing: "True"
    #     opentracing-tracer: "/usr/local/lib/libjaegertracing_plugin.so"
    #     opentracing-tracer-config: |
    #             {
    #                 "service_name": "nginx-ingress",
    #                 "propagation_format": "w3c",
    #                 "sampler": {
    #                     "type": "const",
    #                     "param": 1
    #                 },
    #                 "reporter": {
    #                     "localAgentHostPort": "jaeger-agent.monitoring.svc.cluster.local:6831"
    #                 }
    #             }
    #     jaeger-collector-host: jaeger.monitoring.svc.cluster.local
    appprotect: 
      enable: true
    appprotectdos:
      enable: true
    enableSnippets: true
    image:
      repository: ghcr.io/aknot242/nginx-plus-ingress
      tag: 2.3.0-SNAPSHOT-979db22
    nginxplus: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
    serviceAccount:
      imagePullSecretName: ghcr
  prometheus:
    create: true