elasticsearch:
  antiAffinity: soft
  extraEnvs:
    - name: TZ
      value: America/Los_Angeles
  extraInitContainers:
    - name: init-data
      image: busybox
      command:
        - sh
        - -c
        - |
          #!/bin/bash
          echo "Hello from the postStart handler" > /usr/share/message
          ES_URL=http://elasticsearch-master-0:9200
          git clone https://github.com/skenderidis/nap-dashboard.git
          cd nap-dashboard
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
          curl -X PUT "$ES_URL/signatures" -H 'Content-Type: application/json'
          curl -d "@elastic/signature-mapping.json" -X PUT "$ES_URL/signatures/_mapping" -H 'Content-Type: application/json'
          python3 signatures/upload-signatures.py signatures/signatures-report.json elasticsearch-master-0
          curl -d "@elastic/template-mapping.json" -H 'Content-Type: application/json' -X PUT "$ES_URL/_template/waf_template?include_type_name"
          curl -d "@elastic/template-mapping.json" -H 'Content-Type: application/json' -X PUT "$ES_URL/_template/waf_template?include_type_name"
          curl -d "@elastic/enrich-policy.json" -H 'Content-Type: application/json' -X PUT "$ES_URL/_enrich/policy/signatures-policy"
          curl -d "@elastic/sig-lookup.json" -H 'Content-Type: application/json' -X PUT "$ES_URL/_ingest/pipeline/sig_lookup"
